"""empty message

Revision ID: 03aea7e3b890
Revises: 
Create Date: 2021-05-03 06:32:04.995887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.


revision = '03aea7e3b890'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    articles = op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('creator', sa.String(), nullable=True),
    sa.Column('image_src', sa.String(), nullable=True),
    sa.Column('link_src', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('keywords', sa.String(), nullable=True),
    sa.Column('media_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    users = op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('messenger_id', sa.String(), nullable=True),
    sa.Column('keywords', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    reading = op.create_table('reading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('attention', sa.Integer(), nullable=True),
    sa.Column('like', sa.Integer(), nullable=True),
    sa.Column('refused', sa.Integer(), nullable=True),
    sa.Column('read', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    questions = op.create_table('questions',
                                sa.Column('id', sa.Integer(), nullable=False),
                                sa.Column('news_id', sa.Integer(), nullable=True),
                                sa.Column('question_text', sa.String(), nullable=True),
                                sa.Column('question_type', sa.Integer(), nullable=True),
                                sa.Column('order', sa.Integer(), nullable=True),
                                sa.ForeignKeyConstraint(['news_id'], ['articles.id'], ),
                                sa.PrimaryKeyConstraint('id')
                                )
    score = op.create_table('score',
                            sa.Column('id', sa.Integer(), nullable=False),
                            sa.Column('user_id', sa.Integer(), nullable=True),
                            sa.Column('key_word', sa.String(), nullable=True),
                            sa.Column('score', sa.Integer(), nullable=True),
                            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                            sa.PrimaryKeyConstraint('id')
                            )
    answers = op.create_table('answers',
                              sa.Column('id', sa.Integer(), nullable=False),
                              sa.Column('question_id', sa.Integer(), nullable=True),
                              sa.Column('answer_text', sa.String(), nullable=True),
                              sa.Column('correct_answers', sa.Boolean(), nullable=True),
                              sa.Column('correct_answer_text', sa.String(), nullable=True),
                              sa.Column('order', sa.Integer(), nullable=True),
                              sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
                              sa.PrimaryKeyConstraint('id')
                              )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reading')
    op.drop_table('users')
    op.drop_table('articles')
    op.drop_table('answers')
    op.drop_table('score')
    op.drop_table('questions')
    # ### end Alembic commands ###
