"""empty message

Revision ID: 3a2f5c3db80f
Revises: 03aea7e3b890
Create Date: 2021-09-08 19:23:34.628261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3a2f5c3db80f"
down_revision = "03aea7e3b890"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("score", sa.Column("date", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("score", "date")
    # ### end Alembic commands ###
