"""empty message

Revision ID: c76e9d46ee22
Revises: 03aea7e3b890
Create Date: 2021-06-06 07:01:30.185122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c76e9d46ee22'
down_revision = '03aea7e3b890'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    questions = op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=True),
    sa.Column('question_text', sa.String(), nullable=True),
    sa.Column('question_type', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['news_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('key_word', sa.String(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    answers = op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('answer_text', sa.String(), nullable=True),
    sa.Column('correct_answers', sa.Boolean(), nullable=True),
    sa.Column('correct_answer_text', sa.String(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    op.bulk_insert(questions, [
        {'id': '1117', 'news_id': '1', 'question_text': 'Jak často se downův syndrom u narozených dětí vyskytuje?',
         ' text': 'A', 'question_type': '1', ' order': None},
        {'id': '1118', 'news_id': '1','question_text': 'Jste pro integraci lidí s downovým sysndromem do běžného zaměstnaní a vzdělá',
        ' text': 'A', 'question_type': '2', ' order': None},
        {'id': '1119', 'news_id': '2', 'question_text': 'Kdy se otevře možnost registrace na očkování pro všechny?',
         ' text': 'A', 'question_type': '1', ' order': None},
        {'id': '1120', 'news_id': '2', 'question_text': 'Je podle Vás rychlost očkování dostatečná?', ' text': 'A',
         'question_type': '2', ' order': None}]
                   )
    op.bulk_insert(answers, [
        {'id': '11119', 'question_id': '1117', 'correct_answer': '0', 'answer_text': 'Každé 100. dítě', 'order': '1'},
        {'id': '11129', 'question_id': '1117', 'correct_answer': '1', 'answer_text': 'Každé 700. dítě', 'order': '2'},
        {'id': '11139', 'question_id': '1117', 'correct_answer': '0', 'answer_text': 'Každé 3000. dítě', 'order': '3'},
        {'id': '11149', 'question_id': '1118', 'correct_answer': '1', 'answer_text': 'Ano', 'order': '1'},
        {'id': '11159', 'question_id': '1118', 'correct_answer': '1', 'answer_text': 'Ne', 'order': '2'},
        {'id': '11169', 'question_id': '1119', 'correct_answer': '0', 'answer_text': '5/25/2021', 'order': '1'},
        {'id': '11179', 'question_id': '1119', 'correct_answer': '1', 'answer_text': '7/1/2021', 'order': '2'},
        {'id': '11189', 'question_id': '1119', 'correct_answer': '0', 'answer_text': '9/1/2021', 'order': '3'},
        {'id': '11199', 'question_id': '1120', 'correct_answer': '1', 'answer_text': 'Ano, je dostatečná',
         'order': '1'},
        {'id': '11209', 'question_id': '1120', 'correct_answer': '1', 'answer_text': 'Ne, není', 'order': '2'}]
                   )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answers')
    op.drop_table('score')
    op.drop_table('questions')
    # ### end Alembic commands ###
